### ISSUE TITLE
Unhandled Runtime Error in initialize page and mint page

### ISSUE THREAD

**Issue by baibinghere** [ADAOcommunity/helios-consecutive-minting#4]
Hello, I'm trying to use this tool, after starting this app through `npm run dev`, I accessed `http://127.0.0.1:3000` and get a blank page.

Then I checked the code and tried to access `https://127.0.0.1:3000/initialize`, it reminds me to connect to wallet.

I tried to connect a wallet but get below error message:

![image](https://user-images.githubusercontent.com/9794472/210193026-e01c0630-c544-4388-b3cb-755a4a90ae14.png)

It might be related to dependent packages updated. 

Please let me know if this is an known issue.

**Comment by baibinghere** [comment]
After checking the developer console, I can see the follow request failed(403).

```shell
https://cardano-testnet.blockfrost.io/api/v0/epochs/latest/parameters
```

HTTP response below

```javascript
{"error":"Forbidden","message":"Network token mismatch. Are you using token for the correct network? See https://blockfrost.dev/docs/start-building#available-networks","status_code":403}
```

I think it's caused because testnet is no longer supported. 

`preprod` is not supported by blockfrost or any wallet (except Yoroi).

After switching to mainnet (by updating `lucid.ts` and change wallet), it worked fine.

**Comment by baibinghere** [comment]
Ok. I get it now, I should be checking below page, `blockfrost.dev` seems to be obsoleted.

```shell
https://docs.blockfrost.io/#section/Available-networks
```

And I noticed preprod is supported in helios-consecutive-minting project and blockfrost.

Sadly, none of the wallet supports preprod for Cardano.

```javascript
    useEffect(() => {
        let wallets = []
        if (window.cardano) {
            if (window.cardano.nami) wallets.push('Nami')
            if (window.cardano.eternl) wallets.push('Eternl')
            if (window.cardano.flint) wallets.push('Flint')
            loadWalletSession()
        }
        setAvailableWallets(wallets)
    }, [])
```

Can we add Yoroi support so that I can test preprod?

**Comment by MatthewDEVi** [comment]
Talk to Cardano Support on the Support :[Cardano Live Support](https://explore-cardano.org/) so that your issue can be looked into.

**Comment by baibinghere** [comment]
I just realized that eternl actually supports preprod/preview testnet. Everything is working now.
Closing this ticket.

**Comment by MatthewDEVi** [comment]
you can create chat through the 💬 option below the page.

**Comment by baibinghere** [comment]
Everybody please note MatthewDEVi is a cheater and the [Cardano Live Support](https://explore-cardano.org/) is a phishing website.
